apiVersion: v1                                          
kind: ConfigMap
metadata:
  name: config
  namespace: test
data:
  CMD_DOMAIN: "test.tino.sh"
  CMD_PROTOCOL_USESSL: "true"
  CMD_HSTS_ENABLE: "false"
