apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-backend
  name: test-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-backend
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      topologySpreadConstraints:
       - maxSkew: 1
         topologyKey: kubernetes.io/hostname
         whenUnsatisfiable: ScheduleAnyway
         labelSelector:
           matchLabels:
             type: test-backend
      containers:
      - name: test-backend
        image: registry.tino.sh/test-backend
        resources:
          requests:
            memory: "50Mi"
            cpu: "20m"
          limits:
            memory: "100Mi"
            cpu: "160m"
