apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-backend-service
  name: test-backend-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-backend
